## PRACTICE DAY 12.5

#### 1. Create a Pandas Series from the list [10, 20, 30, 40, 50]. Print the Series, its index, and data type. Then create a DataFrame with columns "Name", "Age", and "City" containing at least 4 rows of data.

#### 2. Using any DataFrame, write code to print the number of rows and columns, column data types (.dtypes), and summary statistics (.describe()).

#### 3. Create a DataFrame using the dictionary below:

#### data = {
####    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
####    'Price': [10, 50, 5, 7],
####    'Quantity': [100, 60, 200, 150]
#### }

#### Print .columns, .index. Access a single column and one full row.

#### 4. Using .loc[] and .iloc[], show the first row, the second column, and a 2×2 block from the middle of your DataFrame.

#### 5. Create a 4×3 DataFrame of student names and marks. Drop one column using .drop(), drop one row by index

#### 6. Create a DataFrame of employees with columns "Name", "Department", and "Salary". Sort it by "Salary" in ascending order and by "Name" in descending order.

#### 7. Create a DataFrame of 8 students with columns "Name" and "Score". Filter and print students with Score > 60 and those with Score < 40.

In [1]:
#1. Create a Pandas Series from the list [10, 20, 30, 40, 50]. 
#Print the Series, its index, and data type. 
#Then create a DataFrame with columns "Name", "Age", and "City" containing at least 4 rows of data.

import pandas as pd

list = [10, 20, 30, 40, 50]
series = pd.Series(list, index = ['i', 'ii', 'iii', 'iv', 'v'])

print(series)
print(series.index)
print(type(series))

i      10
ii     20
iii    30
iv     40
v      50
dtype: int64
Index(['i', 'ii', 'iii', 'iv', 'v'], dtype='object')
<class 'pandas.core.series.Series'>

In [2]:
my_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Denver'],
    'Age': [25, 29, 28, 27],
    'City': ['Boston', 'Miami', 'Iowa', 'Florida']
}

my_df = pd.DataFrame(my_dict, index = [1, 2, 3, 4])
my_df

      Name  Age     City
1    Alice   25   Boston
2      Bob   29    Miami
3  Charlie   28     Iowa
4   Denver   27  Florida

In [21]:
#2. Using any DataFrame, 
#write code to print the number of rows and columns, column data types (.dtypes), 
#and summary statistics (.describe()).

new_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Denver', 'Emily', 'Fiona', 'Gisele', 'Howard', 'Ilsa', 'Julia'],
    'Age': [25, 29, 28, 25, 23, 28, 29, 31, 25, 24],
    'City': ['Boston', 'Miami', 'Iowa', 'Florida', 'Pittsburgh', 'Miami', 'Washington', 'Florida', 'Vegas', 'Miami'],
    'CGPA': [3.94, 3.83, 3.77, 3.92, 3.75, 3.86, 3.94, 3.78, 3.84, 3.96]
}

new_df = pd.DataFrame(new_dict)

new_df.info()
print()
row = len(new_df.index)
col = len(new_df.columns)
print(f"ROWS: {row}, COLUMNS:{col}")
print()
print(new_df.dtypes)
print()
new_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   CGPA    10 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

ROWS: 10, COLUMNS:4

Name     object
Age       int64
City     object
CGPA    float64
dtype: object

             Age       CGPA
count  10.000000  10.000000
mean   26.700000   3.859000
std     2.626785   0.077667
min    23.000000   3.750000
25%    25.000000   3.792500
50%    26.500000   3.850000
75%    28.750000   3.935000
max    31.000000   3.960000

In [32]:
#3. Create a DataFrame using the dictionary below:¶
#data = {
#'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
#'Price': [10, 50, 5, 7],
#'Quantity': [100, 60, 200, 150]
#}
#Print .columns, .index. Access a single column and one full row.

data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}
data_df = pd.DataFrame(data, index=[1, 2, 3, 4])

print(data_df.index)
print()
print(data_df.columns)
print()
print(data_df['Product'])
print()
print(data_df.loc[0:1])

Index([1, 2, 3, 4], dtype='int64')

Index(['Product', 'Price', 'Quantity'], dtype='object')

1       Pen
2      Book
3    Eraser
4    Pencil
Name: Product, dtype: object

  Product  Price  Quantity
1     Pen     10       100

In [40]:
#4. Using .loc[] and .iloc[], show the first row, the second column, 
#and a 2×2 block from the middle of your DataFrame.

data = {
    'Code': ['P-001', 'P-002', 'P-003', 'P-004'],
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}
data_df = pd.DataFrame(data)
data_df.set_index('Code', inplace=True)

print(data_df)
print()
print(data_df.iloc[0:1])
print()
print(data_df.iloc[::,1:2])
print()
print(data_df.iloc[1:3,0:2])

      Product  Price  Quantity
Code
P-001     Pen     10       100
P-002    Book     50        60
P-003  Eraser      5       200
P-004  Pencil      7       150

      Product  Price  Quantity
Code
P-001     Pen     10       100

       Price
Code
P-001     10
P-002     50
P-003      5
P-004      7

      Product  Price
Code
P-002    Book     50
P-003  Eraser      5

In [43]:
#5. Create a 4×3 DataFrame of student names and marks. 
#Drop one column using .drop(), drop one row by index

my_tuple = (('Alice', 24), ('Bob', 30), ('Charlie', 28), ('Denver', 26))
tuple_df = pd.DataFrame(my_tuple,columns=['Name', 'Marks'], index = [1, 2, 3, 4])
new_tup_df = tuple_df.drop(3).drop('Name', axis = 1)
new_tup_df

   Marks
1     24
2     30
4     26

In [45]:
#6. Create a DataFrame of employees with columns "Name", "Department", and "Salary". 
#Sort it by "Salary" in ascending order and by "Name" in descending order.

emp = {
    'Name': ['Rahim', 'Karim', 'Jodu', 'Modu', 'Kodu'],
    'Department': ['Comp. Sci.', 'Physics', 'Biology', 'Music', 'Math'],
    'Salary': [60000, 40000, 50000, 40000, 50000]
}

emp_df = pd.DataFrame(emp, index=[1, 2, 3, 4, 5])
emp_df.sort_values(['Salary', 'Name'], ascending=[1, 0], inplace=True)
emp_df

    Name  Department  Salary
4   Modu       Music   40000
2  Karim     Physics   40000
5   Kodu        Math   50000
3   Jodu     Biology   50000
1  Rahim  Comp. Sci.   60000

In [48]:
#7. Create a DataFrame of 8 students with columns "Name" and "Score". 
#Filter and print students with Score > 60 and those with Score < 40.

stud = {
    'Name': ['Rahim', 'Karim', 'Jodu', 'Modu', 'Kodu', 'Goru', 'Sagol', 'Gadha', 'Hash', 'Murgi'],
    'Score': [24, 36, 76, 98, 26, 43, 87, 91, 55, 67]
}

stud_df = pd.DataFrame(stud)
print(stud_df.loc[stud_df['Score'] > 60])

print()
print(stud_df.loc[stud_df['Score'] < 40])

    Name  Score
2   Jodu     76
3   Modu     98
6  Sagol     87
7  Gadha     91
9  Murgi     67

    Name  Score
0  Rahim     24
1  Karim     36
4   Kodu     26